window.OPENIGHT_CONFIG={
  API_URL:"PASTE_GOOGLE_APPS_SCRIPT_WEB_APP_URL_HERE",
  WHATSAPP_OPENIGHT:"393520840632",
  WHATSAPP_YOURPARTY:"393517854352",
  OPENWINGS_URL:"https://openwingstrip.com",
  YOURPARTY_URL:"https://yourparty.it"
};
